Pandas

In [10]:
import pandas as pd


In [26]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [28]:
data = [ 1,2,3,4]
i = ['a','b','c','d']
series = pd.Series(data, index=i)
print(series)

a    1
b    2
c    3
d    4
dtype: int64


In [30]:
data = {'a':10, 'b':20, 'c':30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [32]:
series.replace(20,100)

a     10
b    100
c     30
dtype: int64

In [34]:
import numpy as np

data = np.array([100,200,300])
series = pd.Series(data, index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


#pandas dataframe

In [37]:
import pandas as pd
data = {"name":['alice','bob','mary'],'age': [25,30,34],'country':["usa","uk","aus"]}
df = pd.DataFrame(data)
print(df)

    name  age country
0  alice   25     usa
1    bob   30      uk
2   mary   34     aus


In [41]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['a','b','c'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


In [43]:
data = [[1,"Alice",25],[2,"BOb",30],[3,'marry',34]]
print(data)
df = pd.DataFrame(data, columns=['id','name','age'])
print(df)

[[1, 'Alice', 25], [2, 'BOb', 30], [3, 'marry', 34]]
   id   name  age
0   1  Alice   25
1   2    BOb   30
2   3  marry   34


In [3]:
import pandas as pd
data = [[1,"Alice",25],[2,"BOb",30],[3,'marry',34]]
print(data)
df = pd.DataFrame(data, columns=['id','name','age'])
print(df)

[[1, 'Alice', 25], [2, 'BOb', 30], [3, 'marry', 34]]
   id   name  age
0   1  Alice   25
1   2    BOb   30
2   3  marry   34


In [19]:
import pandas as pd
iris_df = pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [21]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [27]:
iris_df = pd.read_excel("iris.xlsx")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [29]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [25]:
iris_df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [31]:
print(iris_df.shape)
print(iris_df.ndim)
print(iris_df.size)

(150, 5)
2
750


In [33]:
iris_df.iloc[10:21,:]

sepal.length  sepal.width  petal.length  petal.width variety
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa

In [37]:
import numpy as np
iris_array=np.array(iris_df)
iris_array

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [5.0, 3.0, 1.6, 0.

In [47]:
iris_df[["sepal.length", "petal.width"]]

sepal.length  petal.width
0             5.1          0.2
1             4.9          0.2
2             4.7          0.2
3             4.6          0.2
4             5.0          0.2
..            ...          ...
145           6.7          2.3
146           6.3          1.9
147           6.5          2.0
148           6.2          2.3
149           5.9          1.8

[150 rows x 2 columns]

In [53]:
data = {"weight":[66,75,84,96,48,71], \
        "height":[156,165,186,165,174,167]}
bmi = pd.DataFrame(data)
bmi

weight  height
0      66     156
1      75     165
2      84     186
3      96     165
4      48     174
5      71     167

In [59]:
#create bmi column
bmi['BMI']=bmi['weight']/(bmi['height']/100)**2
bmi

weight  height        BMI
0      66     156  27.120316
1      75     165  27.548209
2      84     186  24.280264
3      96     165  35.261708
4      48     174  15.854142
5      71     167  25.458066

In [61]:
bmi.loc[3]=[78,np.nan,np.nan]
bmi

weight  height        BMI
0      66   156.0  27.120316
1      75   165.0  27.548209
2      84   186.0  24.280264
3      78     NaN        NaN
4      48   174.0  15.854142
5      71   167.0  25.458066

In [63]:
bmi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   weight  6 non-null      int64  
 1   height  5 non-null      float64
 2   BMI     5 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 276.0 bytes


In [65]:
bmi.isnull().sum()


weight    0
height    1
BMI       1
dtype: int64

In [67]:
bmi['weight'] =bmi['weight'].fillna(165)
bmi

weight  height        BMI
0      66   156.0  27.120316
1      75   165.0  27.548209
2      84   186.0  24.280264
3      78     NaN        NaN
4      48   174.0  15.854142
5      71   167.0  25.458066

In [69]:
bmi['height'] =bmi['height'].fillna(78)
bmi

weight  height        BMI
0      66   156.0  27.120316
1      75   165.0  27.548209
2      84   186.0  24.280264
3      78    78.0        NaN
4      48   174.0  15.854142
5      71   167.0  25.458066